# SQLite version 3.x
development:
  adapter: mysql
  database: contest_dev 
  encoding: utf8
  username: contest
  password: testcon
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: contest_test
  encoding: utf8
  username: contest
  password: testcon
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: contest_pro 
  encoding: utf8
  username: contest
  password: testcon
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

